version: "3.8"

networks:
  default:
    external:
      name: vulnvision

services:
  # django_httpx service
  vulnvision_rabbitmq_broker:
    build:
      context: .
      dockerfile: Dockerfile
    image: vulnvision_rabbitmq_broker:latest
    container_name: vulnvision_rabbitmq_broker
    restart: always
    # command: python manage.py runserver 0.0.0.0:8002
    ports:
      - 15672:15672
      - 5672:5672
